# Generated by Django 4.2.11 on 2024-04-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="categories",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
