# Generated by Django 4.2.11 on 2024-04-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chart", "0003_gamereviewers_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_code",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamereviewers",
            name="game_code",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="topsellers",
            name="game_code",
            field=models.IntegerField(default=0),
        ),
    ]
